#!/usr/bin/env python3

from rawkit.raw import Raw
from photolib import Image
import sys

if len(sys.argv) != 2:
    print("too many or too few arguments (expected one)")

print(Image.from_file(sys.argv[1]))
